terraform/src/src/src/Entity/Company.php
<?php

namespace App\Entity;

use App\Repository\CompanyRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CompanyRepository::class)
 */
class Company
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $comdescription;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $comlogo;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getComdescription(): ?string
    {
        return $this->comdescription;
    }

    public function setComdescription(string $comdescription): self
    {
        $this->comdescription = $comdescription;

        return $this;
    }

    public function getComlogo(): ?string
    {
        return $this->comlogo;
    }


    public function getComlogoUrl(): ?string
    {
        return 'assets/img/' . $this->comlogo;
    }

    public function setComlogo(?string $comlogo): self
    {
        $this->comlogo = $comlogo;

        return $this;
    }

    public function __toString(): string
    {
        return $this->name;
    }
}

terraform/src/src/src/Form/CompanyType.php
<?php

namespace App\Form;

use App\Entity\Company;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Image;
use Symfony\Component\Validator\Constraints\NotNull;

class CompanyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $company = $options['data'] ?? null;
        $isEdit = $company->getComlogo();
        $message  = $isEdit;

        $imageConstraints[] = new Image([
            'maxSize' => '1024k',
            'mimeTypes' => [
                'image/jpeg',
                'image/png',
                'image/jpeg',
            ],
            'mimeTypesMessage' => 'Please upload a valid Img Format',
        ]);

        if (null === $isEdit) {
            $imageConstraints[] = new NotNull([
                'message' => 'Please upload an image',
            ]);
            $message = 'Select an Company image';
        }

        $builder
            ->add('name', TextType::class, [
                'label' => 'Company name'
            ])
            ->add('comdescription', TextareaType::class, [
                'label' => 'Company description',
                'attr' => ['rows' => 6]
            ])
            ->add('comlogo', FileType::class, [
                'attr' => [
                    'placeholder' => $message,
                ],
                'label' => 'Company logo',
                'required' => false,
                'mapped' => false,
                'constraints' => $imageConstraints,


            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Company::class,
        ]);
    }
}

terraform/src/src/src/Controller/Experience/CompanyController.php
<?php

namespace App\Controller\Experience;

use App\Entity\Company;
use App\Form\CompanyType;
use App\Repository\CompanyRepository;
use App\Repository\ExperienceRepository;
use App\Service\FileUploader;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/company")
 * @IsGranted("ROLE_USER")
 */
class CompanyController extends AbstractController
{
    /**
     * @Route("/", name="app_company_index", methods={"GET"})
     */
    public function index(CompanyRepository $companyRepository, Request $request, PaginatorInterface $paginator, ExperienceRepository $experienceRepository): Response
    {

        $q = $request->query->get('q');
        $user_id = $this->getUser()->getId();

        $queryBuilder = $companyRepository->getCompanyByUser($q, $user_id, $experienceRepository);

        $paginator = $paginator->paginate(
            $queryBuilder,
            $request->query->getInt('page', 1),
            5
        );
        dump($paginator);
        return $this->render('company/index.html.twig', [
            'pagination' => $paginator,
        ]);
    }

    /**
     * @Route("/new", name="app_company_new", methods={"GET","POST"})
     */
    public function new(Request $request, FileUploader $fileUploader): Response
    {
        $company = new Company();
        $form = $this->createForm(CompanyType::class, $company);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            $logo = $form->get('comlogo')->getData();
          
            if ($logo) {
                $fileName = $fileUploader->upload($logo);
                $company->setComlogo($fileName);
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($company);
                $entityManager->flush();
                return $this->redirectToRoute('app_company_index');
            }


            
        }

        return $this->render('company/new.html.twig', [
            'company' => $company,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_company_show", methods={"GET"})
     */
    public function show(Company $company): Response
    {
        return $this->render('company/show.html.twig', [
            'company' => $company,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_company_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Company $company, FileUploader $fileUploader): Response
    {
        $form = $this->createForm(CompanyType::class, $company);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $logo = $form->get('comlogo')->getData();
            if ($logo) {
                $fileName = $fileUploader->upload($logo);
                $company->setComlogo($fileName);
            }
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('app_company_index');
        }

        return $this->render('company/edit.html.twig', [
            'company' => $company,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_company_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Company $company): Response
    {
        if ($this->isCsrfTokenValid('delete' . $company->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($company);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_company_index');
    }
}

terraform/src/src/templates/company/_delete_form.html.twig
<div class="col-sm-12 col-lg-12 text-right">
  <form
    method="post"
    action="{{ path('app_company_delete', { id: company.id }) }}"
    onsubmit="return confirm('Are you sure you want to delete this item?');"
  >
    <input type="hidden" name="_method" value="DELETE" />
    <input
      type="hidden"
      name="_token"
      value="{{ csrf_token('delete' ~ company.id) }}"
    />
    <button class="btn btn-danger text-right">Delete</button>
  </form>
</div>

terraform/src/src/templates/company/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-block btn-info">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

terraform/src/src/templates/company/edit.html.twig
{% extends 'base/base.html.twig' %} {% block title %}
Edit Company 
{% endblock %} 
 

{% block body %}
<div class="row justify-content-center">
    <div class="col-sm-12 col-lg-6">
   <h1>Edit Company</h1>

    {{ include('company/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="btn btn-warning"  href="{{ path('app_company_index') }}">back to list</a>

    {{ include('company/_delete_form.html.twig') }}
</div>
</div>

 
{% endblock %}

terraform/src/src/templates/company/index.html.twig
{% extends 'base/base.html.twig' %}
{% block title %}
	Company
{% endblock %}
{% block body %}


	{% for message in app.flashes('success') %}
		<div class="alert alert-success w-100">
			<h3>{{ message }}</h3>
		</div>
	{% endfor %}
	<div class="col-xs-7 col-sm-7 p-2 col-md-7 col-lg-12 text-left">
		<h3>Company index</h3>
		<hr/>
	</div>

	<div class="row justify-content-center p-2">
		<div class="col-xs-4 col-sm-4 col-md-4 col">
			<form class="row text-left">
				<input class="form-control col" value="{{ app.request.query.get('q') }}" name="q" type="search" placeholder="Search" aria-label="Search"/>
				<button class="col-lg-2 btn btn-outline-light my-2 my-sm-0" type="submit">
					Search
				</button>
			</form>
		</div>
	</div>

	<div class="col-lg-12 table-responsive">
		<table class="table table-striped text-white table-bordered">
			<thead class="thead-dark">
				<tr>
					<th>
						<div class="col-sm-2">#</div>
					</th>
					<th scope="col">Id</th>
					<th scope="col">Name</th>
					<th scope="col">Comdescription</th>
					<th scope="col">Photo</th>
					<th scope="col">Comlogo</th>
					<th class="text-center" scope="col">actions</th>
				</tr>
			</thead>
			<tbody>


				{% for company in pagination %}


					<tr>
						<td>#</td>
						<td>{{ company.expcompany.id }}</td>
						<td>{{ company.expcompany.name }}</td>
						<td>{{ company.expcompany.comdescription| truncate }}</td>
						<td class="text-center">
							<a><img src="{{ asset(company.expcompany.comlogoUrl) }}" class="" alt="" height="50px"></a>
						</td>
						<td>{{ company.expcompany.comlogo }}</td>
						<td>
							<div class="row">
								<div class="col col-lg-6">
									<a class="btn btn-block btn-success" href="{{ path('app_company_show', { id: company.expcompany.id }) }}">show</a>
								</div>
								<div class="col col-lg-6">
									<a class="btn btn-block btn-info" href="{{ path('app_company_edit', { id: company.expcompany.id }) }}">edit</a>
								</div>
							</div>
						</td>
					</tr>
				{% else %}
					<tr>
						<td colspan="9">no records found</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
	<div class="col">
		<div class="d-flex justify-content-end">
		 
			{{ knp_pagination_render(pagination) }}

		</div>
		<div class="d-flex justify-content-center">
			<a class="btn btn-outline-light btn-block" href="{{ path('app_company_new') }}">Create new</a>
		</div>
	</div>


{% endblock %}

terraform/src/src/templates/company/new.html.twig
{% extends 'base/base.html.twig' %}
{% block title %}
	Company new

{% endblock %}
{% block body %}

	<div class="row justify-content-center">
		<div class="col-sm-12 col-lg-6">
			<h1>Create new Company</h1>

			{{ include('company/_form.html.twig') }}

			<a class="btn btn-warning" href="{{ path('app_company_index') }}">back to list</a>

		</div>
	</div>


{% endblock %}

terraform/src/src/templates/company/show.html.twig
{% extends 'base/base.html.twig' %}
{% block title %}
	Company show
{% endblock
%}
{% block body %}
	<div class="col-sm-6 col-lg-12">
		<h1>Company</h1>
		<div class="table-responsive">
			<table class="table table-striped text-white">
				<tbody>
					<tr>
						<th>Id</th>
						<td>{{ company.id }}</td>
					</tr>
					<tr>
						<th>Name</th>
						<td>{{ company.name }}</td>
					</tr>
					<tr>
						<th>Comdescription</th>
						<td>{{ company.comdescription }}</td>
					</tr>
					<tr>
						<th>Comlogo</th>
						<td>
							<img src="{{ asset(company.comlogoUrl) }}" class="" alt="" height="80px"/>
						</td>
					</tr>
				</tbody>
			</table>
		</div>

		<div class="row">
			<div class="col-sm-12 col-lg-6">
				<a class="btn btn-warning btn-block" href="{{ path('app_company_index') }}">back to list</a>
			</div>
			<div class="col-sm-12 col-lg-6">
				<a class="btn btn-info btn-block" href="{{ path('app_company_edit', { id: company.id }) }}">edit</a>
			</div>
		</div>
		<div class="p-3">
			{{ include("company/_delete_form.html.twig") }}
		</div>
	</div>

{% endblock %}